bagisto/bagisto-docs

assets/scss/layout.scss

[Issue Fixed: Sidebar's layout issue resolved.]
https://qsnapnet.com/snaps/8ns6dzt1gwu

[Issue Fixed: Sidebar's layout issue resolved.]

---

_site/data_grid.html
api_cart.md
api_category.md
api_customer.md
api_customer_addresses.md
api_customer_review.md
api_customer_wishlist.md
api_invoice_shipment.md
api_order.md
api_product.md
api_product_review.md
cart_rule.md
data_grid.md

This pull request contains the fixes for #97 API should be in capital letters and fix for issue #98 space should be there between rules and on.

fixes of issues #98 and issues #97 

---

index.md

Download link updated

---

index.md

GHz unit corrected

---

index.md

Unwanted punctuations fixed

---

index.md

- Removed duplicate requirements from the requirements section

Updated Requirements

---

create_package.md
create_payment_method.md
create_shipping_method.md

Updated:
1. Create Package
2. Create Payment Package
3. Create Shipment Package

Dev Docs Documentation Update

---

data_grid.md
events.md

DataGrid and Event Markdown Updated.

DataGrid And Event Markdown Updated

---

index.md

misc. update

---

_includes/sidebar.html
assets/css/syntax.css
index.md

Bug fixed
Fix active inactive links issue #57

Fix active inactive links issue #57

---

index.md

add bagisto:install in index page https://github.com/bagisto/bagisto/pull/2032

add bagisto:install in index page #2032

---

docs/1.x/api/invoices.md
docs/1.x/api/orders.md
docs/1.x/api/reviews.md
docs/1.x/api/shipments.md

Removed admin text because this confused the user that this API is for admin as well.
Link: https://github.com/bagisto/bagisto/issues/4176

Some Editing Done

---

docs/1.x/introduction/installation.md

Standard Docs Removed

---

docs/1.x/introduction/installation.md

Composer Installation For Bagisto Added

Composer Installation For Bagisto Added

---

docs/.vuepress/version-configs/1.x.js
docs/1.x/themes/integrate-image-search-in-theme.md

Link: https://github.com/bagisto/bagisto-docs/issues/220

Implementation For Image Search Docs Added #220

---

docs/1.x/api/customers.md
docs/1.x/api/getting-started-with-the-api.md

Link: https://github.com/bagisto/bagisto/issues/4551#issuecomment-773849697

Some Mistakes Fixed #4551

---

docs/1.x/packages/create_custom_configuration.md

Link: https://github.com/bagisto/bagisto-docs/issues/226

Supported Field Types Added #226

---

docs/1.x/api/wishlists.md

Link: https://github.com/bagisto/bagisto-docs/issues/234

Wishlist Remove Documentation Added #234

---

docs/1.x/api/cart.md

Multiple Product In Cart Docs Added #227

---

docs/.vuepress/version-configs/1.x.js
docs/1.x/api/transactions.md

Added docs which are related to transactions #229

---

docs/.vuepress/version-configs/1.x.js
docs/1.x/api/locales.md

Link: https://github.com/bagisto/bagisto-docs/issues/125

Locales API Doc Added #125

---

package-lock.json
package.json

Vuepress updated to V1.8.2 #238

---

docs/.vuepress/version-configs/1.x.js
docs/1.x/themes/customize-hompepage-menu.md

Added home page menu information in the documentation #112

---

docs/.vuepress/version-configs/1.x.js
docs/1.x/packages/README.md
docs/1.x/packages/add_menu_in_admin.md
docs/1.x/packages/create_acl.md
docs/1.x/packages/create_custom_configuration.md
docs/1.x/packages/create_migrations.md
docs/1.x/packages/create_models.md

- Some enhancement done in the package development section.

Package Development Section Enhanced

---

docs/1.x/advanced/create_shipping_method.md

The previous link is not working. I have updated with new link.

Update link on create_shipping_method.md

---

docs/1.x/advanced/datagrid.md

Link: https://github.com/bagisto/bagisto-docs/issues/248

Old datagrid docs updated #248

---

docs/.vuepress/version-configs/1.x.js
docs/1.x/graphql_admin_api/README.md
docs/1.x/graphql_admin_api/attribute_families.md
docs/1.x/graphql_admin_api/attribute_groups.md
docs/1.x/graphql_admin_api/attributes.md
docs/1.x/graphql_admin_api/categories.md
docs/1.x/graphql_admin_api/cms.md
docs/1.x/graphql_admin_api/customers.md
docs/1.x/graphql_admin_api/explanation.md
docs/1.x/graphql_admin_api/getting-started-with-the-api.md
docs/1.x/graphql_admin_api/products.md
docs/1.x/graphql_admin_api/promotions.md
docs/1.x/graphql_admin_api/sales.md
docs/1.x/graphql_admin_api/settings.md
docs/1.x/graphql_admin_api/velocity.md
docs/1.x/graphql_shop_api/README.md
docs/1.x/graphql_shop_api/addresses.md
docs/1.x/graphql_shop_api/cart.md
docs/1.x/graphql_shop_api/checkout.md
docs/1.x/graphql_shop_api/compare.md
docs/1.x/graphql_shop_api/downloadable_links.md
docs/1.x/graphql_shop_api/getting-started-with-the-api.md
docs/1.x/graphql_shop_api/homepage.md
docs/1.x/graphql_shop_api/orders.md
docs/1.x/graphql_shop_api/reviews.md
docs/1.x/graphql_shop_api/wishlists.md

added documentation for graphql admin and shop api's

added documentation for graphql admin and shop api's

---

docs/1.x/api/cart.md

Link: Link: https://github.com/bagisto/bagisto-docs/issues/251
- Added some header info for the guest cart.

Added some header info for the guest cart #251

---

docs/1.x/introduction/upgrade_to_latest_bagisto.md

Link: https://github.com/bagisto/bagisto-docs/issues/250

Some pointers added #250

---

.editorconfig
README.md

- `.editorconfig` added.
- Contribution guide updated.

Contribution guide enhanced

---

docs/1.x/introduction/requirements.md

Fixed language issues such as active voice usage, simple tense usage, possessive pronoun usage, etc on https://devdocs.bagisto.com/1.x/introduction/requirements.html#php-configuration.
**Note:** In general, product documentation must be in simple tense & active voice.

language improvements

---

docs/1.x/introduction/README.md

Reviewed and fixed the grammatical mistakes on https://devdocs.bagisto.com/1.x/introduction/.

Fixed grammatical mistakes

---

docs/1.x/introduction/installation.md

Fixed the structure and language issues as needed.
The _Warning!_ text on the [Installation](https://devdocs.bagisto.com/1.x/introduction/installation.html#install-bagisto-using-composer) page needs improvement but I didn't edit it as I am not fully aware of the technicalities.
Need more details for improving it. Thanks!

Improved installation doc page

---

docs/1.x/api/cart.md

- Link: https://github.com/bagisto/bagisto-docs/issues/266

Cart Docs Updated #266

---

docs/1.x/introduction/upgrade-to-latest-bagisto.md

- Changes added for Bagisto's latest version.

Bagisto Version Changes Added

---

docs/.vuepress/version-configs/1.x.js
docs/1.x/advanced/helpers.md

Link: https://github.com/bagisto/bagisto-docs/issues/274

Core Helpers Info Added #274

---

docs/1.x/packages/create-acl.md

Link: https://github.com/bagisto/bagisto-docs/issues/273

Roles And Permissions Info Added #273

---

docs/1.x/api/cart.md

Base URL variable in save payment example

wrong base url variable

---

docs/1.x/introduction/requirements.md

Change minimum PHP from 7.3 to 7.4

Change minimum PHP Version

---

docs/1.x/advanced/security-practice.md

[Updated: password generator link.]

[Updated: password generator link.]

---

docs/1.x/graphql-admin-api/installation.md

[Updated installation guide of graphql api.]

[Updated installation guide of graphql api.]

---

docs/2.x/packages/add-menu-in-admin.md

Fixed Issue #362

---

docs/.vuepress/styles/palette.styl
docs/.vuepress/theme/components/TopNav.vue
docs/.vuepress/theme/layouts/Layout.vue
docs/.vuepress/theme/styles/index.styl
docs/.vuepress/theme/styles/mobile.styl

Added Top Nav Bar for current version information

Added Top Nav Bar for current version information

---

docs/2.x/packages/add-menu-in-admin.md

Fix css class Issue

---

docs/2.x/introduction/installation.md

Add mobile app installation guide.

Add mobile app installation guide.

---

docs/.vuepress/version-configs/2.x.js
docs/2.x/api/README.md
docs/2.x/api/getting-started-with-the-api.md

Added rest API page in 2.x

---

docs/2.x/api/getting-started-with-the-api.md

Updated api page remove token registration

Updated api page remove token registration

---

docs/.vuepress/theme/components/TopNav.vue
docs/.vuepress/theme/layouts/404.vue

Added Redirect link in page not found error page 
Added redirect link in Top-Nav-Bar to switch latest version

Added Redirect link in page not found error page 

---

docs/2.x/advanced/create-shipping-method.md
docs/2.x/advanced/indexing-products-to-elasticsearch.md
docs/2.x/architecture/performance.md
docs/2.x/introduction/README.md
docs/2.x/introduction/installation.md
docs/2.x/packages/create-custom-configuration.md
docs/2.x/packages/datagrid.md
docs/2.x/packages/layouts.md
docs/2.x/themes/create-theme.md

Updated Performance Page In 2.x
Updated Elasticsearch configuration In 2.x
Update Installation process In 2.x.

Updated Documentation for 2.X

---

docs/.vuepress/theme/layouts/404.vue

Added feature to redirect in available pages from error page.
Show the list of version in which current page available.

Added feature to redirect in available pages from error page

---

docs/.vuepress/theme/layouts/404.vue

Fixed build issue

---

docs/.vuepress/theme/components/TopNav.vue
docs/1.5.x/packages/README.md
docs/1.5.x/packages/assets.md
docs/1.5.x/packages/create-migrations.md
docs/1.5.x/packages/create-package.md
docs/1.5.x/packages/localization.md
docs/1.5.x/packages/routes.md
docs/1.5.x/packages/views.md
docs/2.x/packages/README.md
docs/2.x/packages/blade-components.md
docs/2.x/packages/create-migrations.md
docs/2.x/packages/create-package.md
docs/2.x/packages/localization.md
docs/2.x/packages/routes.md
docs/2.x/packages/views.md
docs/2.x/prologue/contribution-guide.md
docs/README.md

Update contribution guide with Tailwind class reordering and Pint tests

Update contribution guide with Tailwind class reordering and Pint tests

---

docs/2.x/packages/blade-components.md

Added component customisation docs

Added component customisation docs

---

docs/.vuepress/theme/components/NavLinks.vue
docs/2.x/advanced/change-email-template.md
docs/2.x/advanced/indexing-products-to-elasticsearch.md
docs/2.x/advanced/security-practice.md
docs/2.x/packages/datagrid.md
docs/2.x/packages/localization.md

Update data grid changes

---

docs/.vuepress/config.js
docs/.vuepress/theme/components/NavLinks.vue
docs/.vuepress/theme/layouts/Layout.vue

Added contact us link

---

docs/2.x/prologue/upgrade-guide.md

Added upgrade guide link

---

docs/2.2/architecture/packages.md
docs/2.2/architecture/performance.md
docs/2.2/packages/controllers.md
docs/2.2/packages/routes.md
docs/2.x/architecture/performance.md
docs/2.x/packages/controllers.md
docs/2.x/packages/routes.md
docs/master/architecture/packages.md
docs/master/architecture/performance.md
docs/master/packages/controllers.md
docs/master/packages/routes.md

Fixed routes and controller and performance section

---

docs/master/packages/layouts.md

- Changed "admin" to "shop"
- Correct path of index.blade.php file

Corrections to layouts.md

---

docs/2.0/themes/create-store-theme.md
docs/2.1/packages/create-system-configuration.md
docs/2.2/packages/create-system-configuration.md

update configuration and theme

update configuration and theme

---

docs/2.0/packages/datagrid.md
docs/2.1/packages/datagrid.md
docs/2.2/packages/datagrid.md
docs/master/packages/datagrid.md

Added changes for datagrid column for master, 2.2, 2.1, and 2.0 branches.

Added changes for datagrid column for master, 2.2, 2.1, and 2.0 branches.

---

docs/1.5.x/introduction/docker.md
docs/1.x/introduction/docker.md
docs/2.0/introduction/docker.md
docs/2.1/introduction/docker.md
docs/2.2/introduction/docker.md
docs/2.x/introduction/docker.md
docs/master/introduction/docker.md

Update Docs for docker installation.

Update Docs for docker installation.

---

docs/.vuepress/theme/components/GoogleTranslate.vue
docs/.vuepress/theme/components/LocaleSwitcher.vue
docs/.vuepress/theme/components/Navbar.vue

Added Translation Functionality

:rocket: Added Translation Functionality

---

docs/.vuepress/theme/components/PageNav.vue
docs/.vuepress/theme/components/SidebarGroup.vue
docs/.vuepress/theme/components/SidebarLinks.vue

Fixed next page redirection and sidebar active page

Fixed next page redirection and sidebar active page

---

docs/.vuepress/theme/components/LocaleSwitcher.vue
docs/.vuepress/theme/components/NavLinks.vue
docs/.vuepress/theme/components/Navbar.vue

Fixed Locale switcher

---

docs/2.3/architecture/packages.md
docs/2.3/introduction/requirements.md
docs/2.3/packages/create-package.md
docs/2.3/prologue/contribution-guide.md
docs/2.3/prologue/upgrade-guide.md
docs/master/architecture/packages.md
docs/master/introduction/requirements.md
docs/master/packages/create-package.md

Update docs of v2.3 and master

---

docs/2.3/themes/create-admin-theme.md
docs/2.3/themes/create-store-theme.md
docs/master/themes/create-admin-theme.md
docs/master/themes/create-store-theme.md

Updated customized theme documentation

Updated customized theme documentation

---

docs/2.3/themes/create-admin-theme.md
docs/2.3/themes/create-store-theme.md
docs/master/themes/create-admin-theme.md
docs/master/themes/create-store-theme.md

Update custom theme setup using resource folder

Update custom theme setup using resource folder

---

docs/.vuepress/version-configs/2.3.js
docs/.vuepress/version-configs/master.js
docs/2.3/themes/custom-theme-package.md
docs/master/themes/custom-theme-package.md

Add docs for custom theme using separate package

Add docs for custom theme using separate package

---

docs/2.0/introduction/requirements.md
docs/2.1/introduction/requirements.md
docs/2.2/introduction/requirements.md
docs/2.3/introduction/requirements.md
docs/2.x/introduction/requirements.md
docs/master/introduction/requirements.md

Added Apache and Nginx configuration

Added Apache and Nginx configuration

---

docs/2.0/api/getting-started-with-the-api.md
docs/2.1/api/getting-started-with-the-api.md
docs/2.2/api/rest-api.md

Rest API Links added to V2.0, V2.1 and V2.2

Rest API links added to other versions as well.

---

docs/2.0/api/getting-started-with-the-api.md
docs/2.1/api/getting-started-with-the-api.md
docs/2.2/api/rest-api.md
docs/2.3/api/rest-api.md
docs/2.x/api/getting-started-with-the-api.md

Shop URL issue fixed
